spring.kafka.bootstrap-servers=localhost:9092
kafka_broker=${spring.kafka.bootstrap-servers}
kafka_group_id=weather-group-1


spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.linger-ms=1


spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=10


logging.level.org.springframework.kafka=INFO
logging.level.com.f4ken0name=DEBUG