version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: github_postgres
    restart: always
    environment:
      POSTGRES_DB: github_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
